services:
  # MongoDB 資料庫
  # mongodb:
  #   image: mongo:7.0
  #   container_name: mongodb
  #   restart: unless-stopped
  #   ports:
  #     - "27018:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: password123
  #     MONGO_INITDB_DATABASE: testdb
  #   volumes:
  #     - mongodb_data:/data/db
  #     - ./mongo-init:/docker-entrypoint-initdb.d
  #   networks:
  #     - app-network

  # FastAPI 後端
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - app-network

  # Naive UI 前端
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: naive-ui-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
